### ISSUE TITLE
Not working on Expo and iOS Simulator

### ISSUE THREAD

**Issue by akaFTS** [SiDevesh/React-Native-FAB#14] opened 2018-10-17 16:48 UTC
The button simply does not appear on screen. Some propType warnings are thrown:

`Warning: Failed prop type: Invalid props.style key 'fontSize' supplied to 'View'.`

`Warning: FAB: type specification of prop 'style' is invalid; the type checker function must return 'null' or an 'Error' but returned a function. You may have forgotten to pass an argument to the type checker creator (arrayOf, instanceOf, objectOf, oneOf,oneOfType, and shape all require an argument).`

**Comment by samdeen** [comment] 2018-11-26 07:53
Were you able to fix the second warning? I am getting this too. The FAB is working though.

**Comment by akaFTS** [comment] 2018-11-26 15:10
No. Since I only needed a very simple button, I gave up and created my own.

**Comment by darkwater84** [comment] 2019-05-29 23:06
replace style: PropTypes.shape with  style: PropTypes.shape({})   in index.js (node_modules)
export default class FAB extends Component {
  static propTypes = {
    buttonColor: PropTypes.string,
    iconTextColor: PropTypes.string,
    onClickAction: PropTypes.func,
    iconTextComponent: PropTypes.element,
    visible: PropTypes.bool,
    snackOffset: PropTypes.number,
    style: PropTypes.shape({}),
  };

**Comment by SiDevesh** [comment] 2019-09-30 04:31
The latest publish version contains the fix for this issue, reopen and let me know if the issue is still unresolved.

**Closed by SiDevesh** 2019-09-30 04:31 UTC
