### ISSUE TITLE
Type specification of prop `style` is invalid

### ISSUE THREAD

**Issue by Edweis** [SiDevesh/React-Native-FAB#19] opened 2019-09-08 15:14 UTC
I put the component in my app render and got : 
```
Warning: FAB: type specification of prop `style` is invalid; the type checker function must return `null` or an `Error` but returned a function. You may have forgotten to pass an argument to the type checker creator (arrayOf, instanceOf, objectOf, oneOf, oneOfType, and shape all require an argument).
```
Do you know how I can turn off the warning or fix the issue ?

Thanks ! 

Using : `"react": "16.8.3",`

**Comment by luisneto98** [comment] 2019-09-10 11:32
I have the same error

**Comment by SiDevesh** [comment] 2019-09-30 04:29
The latest publish version contains the fix for this issue, reopen and let me know if the issue is still unresolved.

**Closed by SiDevesh** 2019-09-30 04:29 UTC
